// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"

	"go-zero-demo/user-rpc/internal/logic"
	"go-zero-demo/user-rpc/internal/svc"
	"go-zero-demo/user-rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UsercenterServer) CreateNewUser(ctx context.Context, in *pb.CreateNewUserReq) (*pb.CommonResp, error) {
	l := logic.NewCreateNewUserLogic(ctx, s.svcCtx)
	return l.CreateNewUser(in)
}

func (s *UsercenterServer) RedisTest(ctx context.Context, in *pb.RedisTestReq) (*pb.CommonResp, error) {
	l := logic.NewRedisTestLogic(ctx, s.svcCtx)
	return l.RedisTest(in)
}
