// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type BusinessListReq struct {
	LastId             int64 `json:"lastId"`
	PageSize           int64 `json:"pageSize"`
	HomestayBusinessId int64 `json:"homestayBusinessId"`
}

type BusinessListResp struct {
	List []Homestay `json:"list"`
}

type CommonResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GuessListReq struct {
}

type GuessListResp struct {
	List []Homestay `json:"list"`
}

type Homestay struct {
	Id                  int64   `json:"id"`
	Title               string  `json:"title"`
	SubTitle            string  `json:"subTitle"`
	Banner              string  `json:"banner"`
	Info                string  `json:"info"`
	PeopleNum           int64   `json:"peopleNum"`           //容纳人的数量
	HomestayBusinessId  int64   `json:"homestayBusinessId"`  //店铺id
	UserId              int64   `json:"userId"`              //房东id
	RowState            int64   `json:"rowState"`            //0:下架 1:上架
	RowType             int64   `json:"rowType"`             //售卖类型0：按房间出售 1:按人次出售
	FoodInfo            string  `json:"foodInfo"`            //餐食标准
	FoodPrice           float64 `json:"foodPrice"`           //餐食价格
	HomestayPrice       float64 `json:"homestayPrice"`       //民宿价格
	MarketHomestayPrice float64 `json:"marketHomestayPrice"` //民宿市场价格
}

type HomestayDetailReq struct {
	Id int64 `json:"id"`
}

type HomestayDetailResp struct {
	Homestay Homestay `json:"homestay"`
}

type HomestayListReq struct {
	Page                 int64  `json:"page"`
	PageSize             int64  `json:"pageSize"`
	SearchKey            string `json:"search_key,optional"`
	PeopleNum            int64  `json:"people_num,optional"` // 注意首字母大写
	HomestayCate         string `json:"homestay_cate,optional"`
	HomestayActivityType string `json:"homestay_activity_type,optional"`
}

type HomestayListResp struct {
	List []Homestay `json:"list"`
	CommonResp
}
