// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"go-zero-mall/pkg/globalkey"
)

var (
	homestayCategoryFieldNames          = builder.RawFieldNames(&HomestayCategory{})
	homestayCategoryRows                = strings.Join(homestayCategoryFieldNames, ",")
	homestayCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(homestayCategoryFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	homestayCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(homestayCategoryFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheHomestayCategoryIdPrefix                   = "cache:homestayCategory:id:"
	cacheHomestayCategoryHomestayIdCategoryIdPrefix = "cache:homestayCategory:homestayId:categoryId:"
)

type (
	homestayCategoryModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *HomestayCategory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*HomestayCategory, error)
		FindOneByHomestayIdCategoryId(ctx context.Context, homestayId int64, categoryId int64) (*HomestayCategory, error)
		Update(ctx context.Context, session sqlx.Session, data *HomestayCategory) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *HomestayCategory) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *HomestayCategory) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*HomestayCategory, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HomestayCategory, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HomestayCategory, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*HomestayCategory, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*HomestayCategory, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultHomestayCategoryModel struct {
		sqlc.CachedConn
		table string
	}

	HomestayCategory struct {
		Id         int64     `db:"id"`
		HomestayId int64     `db:"homestay_id"` // 民宿ID，关联 homestay.id
		CategoryId int64     `db:"category_id"` // 分类ID，关联 category.id
		CreateTime time.Time `db:"create_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"` // 版本号
	}
)

func newHomestayCategoryModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultHomestayCategoryModel {
	return &defaultHomestayCategoryModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`homestay_category`",
	}
}

func (m *defaultHomestayCategoryModel) Insert(ctx context.Context, session sqlx.Session, data *HomestayCategory) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo
	homestayCategoryHomestayIdCategoryIdKey := fmt.Sprintf("%s%v:%v", cacheHomestayCategoryHomestayIdCategoryIdPrefix, data.HomestayId, data.CategoryId)
	homestayCategoryIdKey := fmt.Sprintf("%s%v", cacheHomestayCategoryIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, homestayCategoryRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.HomestayId, data.CategoryId, data.DeleteTime, data.DelState, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.HomestayId, data.CategoryId, data.DeleteTime, data.DelState, data.Version)
	}, homestayCategoryHomestayIdCategoryIdKey, homestayCategoryIdKey)
}

func (m *defaultHomestayCategoryModel) FindOne(ctx context.Context, id int64) (*HomestayCategory, error) {
	homestayCategoryIdKey := fmt.Sprintf("%s%v", cacheHomestayCategoryIdPrefix, id)
	var resp HomestayCategory
	err := m.QueryRowCtx(ctx, &resp, homestayCategoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", homestayCategoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomestayCategoryModel) FindOneByHomestayIdCategoryId(ctx context.Context, homestayId int64, categoryId int64) (*HomestayCategory, error) {
	homestayCategoryHomestayIdCategoryIdKey := fmt.Sprintf("%s%v:%v", cacheHomestayCategoryHomestayIdCategoryIdPrefix, homestayId, categoryId)
	var resp HomestayCategory
	err := m.QueryRowIndexCtx(ctx, &resp, homestayCategoryHomestayIdCategoryIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `homestay_id` = ? and `category_id` = ? and del_state = ? limit 1", homestayCategoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, homestayId, categoryId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomestayCategoryModel) Update(ctx context.Context, session sqlx.Session, newData *HomestayCategory) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	homestayCategoryHomestayIdCategoryIdKey := fmt.Sprintf("%s%v:%v", cacheHomestayCategoryHomestayIdCategoryIdPrefix, data.HomestayId, data.CategoryId)
	homestayCategoryIdKey := fmt.Sprintf("%s%v", cacheHomestayCategoryIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homestayCategoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.HomestayId, newData.CategoryId, newData.DeleteTime, newData.DelState, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.HomestayId, newData.CategoryId, newData.DeleteTime, newData.DelState, newData.Version, newData.Id)
	}, homestayCategoryHomestayIdCategoryIdKey, homestayCategoryIdKey)
}

func (m *defaultHomestayCategoryModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *HomestayCategory) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	homestayCategoryHomestayIdCategoryIdKey := fmt.Sprintf("%s%v:%v", cacheHomestayCategoryHomestayIdCategoryIdPrefix, data.HomestayId, data.CategoryId)
	homestayCategoryIdKey := fmt.Sprintf("%s%v", cacheHomestayCategoryIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, homestayCategoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.HomestayId, newData.CategoryId, newData.DeleteTime, newData.DelState, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.HomestayId, newData.CategoryId, newData.DeleteTime, newData.DelState, newData.Version, newData.Id, oldVersion)
	}, homestayCategoryHomestayIdCategoryIdKey, homestayCategoryIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultHomestayCategoryModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *HomestayCategory) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "HomestayCategoryModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultHomestayCategoryModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultHomestayCategoryModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultHomestayCategoryModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*HomestayCategory, error) {

	builder = builder.Columns(homestayCategoryRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HomestayCategory
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHomestayCategoryModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HomestayCategory, error) {

	builder = builder.Columns(homestayCategoryRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HomestayCategory
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHomestayCategoryModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HomestayCategory, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(homestayCategoryRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*HomestayCategory
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultHomestayCategoryModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*HomestayCategory, error) {

	builder = builder.Columns(homestayCategoryRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HomestayCategory
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHomestayCategoryModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*HomestayCategory, error) {

	builder = builder.Columns(homestayCategoryRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HomestayCategory
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHomestayCategoryModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultHomestayCategoryModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultHomestayCategoryModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	homestayCategoryHomestayIdCategoryIdKey := fmt.Sprintf("%s%v:%v", cacheHomestayCategoryHomestayIdCategoryIdPrefix, data.HomestayId, data.CategoryId)
	homestayCategoryIdKey := fmt.Sprintf("%s%v", cacheHomestayCategoryIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, homestayCategoryHomestayIdCategoryIdKey, homestayCategoryIdKey)
	return err
}
func (m *defaultHomestayCategoryModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheHomestayCategoryIdPrefix, primary)
}
func (m *defaultHomestayCategoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", homestayCategoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultHomestayCategoryModel) tableName() string {
	return m.table
}
