// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	order "go-zero-mall/app/order/service/api/internal/handler/order"
	"go-zero-mall/app/order/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户订单明细
				Method:  http.MethodPost,
				Path:    "/homestayOrder/userHomestayOrderDetail",
				Handler: order.UserHomestayOrderDetailHandler(serverCtx),
			},
			{
				// 用户订单列表
				Method:  http.MethodPost,
				Path:    "/homestayOrder/userHomestayOrderList",
				Handler: order.UserHomestayOrderListHandler(serverCtx),
			},
			{
				// 创建民宿订单
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: order.CreateHomestayOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/order/v1"),
	)
}
