// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package usercenter

import (
	"context"

	"go-zero-demo/user-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp       = pb.CommonResp
	CreateNewUserReq = pb.CreateNewUserReq
	GetUserInfoReq   = pb.GetUserInfoReq
	GetUserInfoResp  = pb.GetUserInfoResp

	Usercenter interface {
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		CreateNewUser(ctx context.Context, in *CreateNewUserReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultUsercenter struct {
		cli zrpc.Client
	}
)

func NewUsercenter(cli zrpc.Client) Usercenter {
	return &defaultUsercenter{
		cli: cli,
	}
}

func (m *defaultUsercenter) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUsercenter) CreateNewUser(ctx context.Context, in *CreateNewUserReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.CreateNewUser(ctx, in, opts...)
}
